### ISSUE TITLE
Follow gem naming conventions

### ISSUE THREAD

**Issue by v0dro** [Arafatk/tensorflow.rb#1]
http://guides.rubygems.org/name-your-gem/

**Comment by v0dro** [comment]
@Arafatk

**Comment by nethsix** [comment]
Putting here for reference, guidelines on how to structure/name 'lib/' and 'ext/' directories:

* http://guides.rubygems.org/make-your-own-gem/
* http://guides.rubygems.org/gems-with-extensions/

**Comment by Arafatk** [comment]
@nethsix @v0dro  Is it okay if I close the issue ?

**Comment by nethsix** [comment]
@Arafatk I'm totally good.
